_core:
  default_config_hash: ijfbzDTN4CbE7Sr-6ubWzy_t1vH4OtU1doNCLssVz-4
langcode: en
uuid: 6e8d35c1-7f5b-47fe-8abd-8f369cc4016e
name: EduDemo
mail: admin@example.com
slogan: 'Learn Without Limits'
page:
  403: ''
  404: ''
  front: /home
admin_compact_mode: false
weight_select_max: 100
default_langcode: en
mail_notification: null
